### ISSUE TITLE
Removing / Uninstalling

### ISSUE THREAD

**Issue by trepidity** [shtirlic/yubikeylockd#5]
It would be nice to have some documentation to remove the service.

I think I was able to do it by changing to the project directory, where I ran the `make` command and running the following command `launchctl unload com.podtynnyi.yubikeylockd.plist`

**Comment by jeantil** [comment]
In the makefile: 
```
install:
		install ./yubikeylockd /usr/local/bin/yubikeylockd
		launchctl unload com.podtynnyi.yubikeylockd.plist
		install ./com.podtynnyi.yubikeylockd.plist  ~/Library/LaunchAgents/com.podtynnyi.yubikeylockd.plist
		launchctl load com.podtynnyi.yubikeylockd.plist
```

so my guess for uninstall would be : 
```
uninstall:
		launchctl unload com.podtynnyi.yubikeylockd.plist
		rm /usr/local/bin/yubikeylockd
		rm ~/Library/LaunchAgents/com.podtynnyi.yubikeylockd.plist
```

**Comment by trepidity** [comment]
makes sense to me. Should I create a PR or would you like to? Your idea :)

**Comment by jeantil** [comment]
feel free to improve over the proposal :)

**Comment by shtirlic** [comment]
Hi, what you you think if I make homebrew formula for the daemon with brew services etc ?

**Comment by jeantil** [comment]
Would be really nice :)

Le ven. 17 févr. 2017 11:21, Serg Podtynnyi <notifications@github.com> a
écrit :

**Comment by shtirlic** [comment]
In recent commits I added Homebrew formula, see updated readme.
